name: 'PR Merged: Build And Release'
on:
  pull_request:
    paths-ignore:
    - '.github/**'
    types: [opened, synchronize, reopened]
    branches:
    - main
    - master
    - stage

permissions:
  contents: write      

jobs:
  build:
   name: Build
   uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Build-Test.yml@main
   with:
      platform: "java"
      command: "mvn clean install -DskipTests"
      
  create_release:
    if: github.event.pull_request.merged == true
    needs: build
    name: Create Tag and Release
    uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Create-Tag-Release.yml@main
    with:
     source_branch: ${{ github.base_ref }}
